### Criar Folha
POST https://localhost:5001/api/folha/criar
Content-Type: application/json

{
    "valorHora" : 25,
    "quantidadeDeHoras" : 100,
    "funcionarioID" : 2
}

### Listar Folhas
GET https://localhost:5001/api/folha/listar

### Buscar
GET https://localhost:5001/api/folha/filtrar/11111111111/10/2022